import { type B2BData } from "./types";

const now = new Date().toISOString();

export const B2B_SEED_DATA: B2BData = {
  pricingTiers: [
    {
      tier: "starter",
      label: "Starter Distributor",
      discountPercent: 7,
      minimumOrderMinor: 10000000,
      quoteReviewHours: 24,
    },
    {
      tier: "growth",
      label: "Growth Partner",
      discountPercent: 12,
      minimumOrderMinor: 30000000,
      quoteReviewHours: 12,
    },
    {
      tier: "enterprise",
      label: "Enterprise Strategic",
      discountPercent: 18,
      minimumOrderMinor: 70000000,
      quoteReviewHours: 6,
    },
  ],
  accounts: [
    {
      id: "b2b-acct-0001",
      companyName: "Prime Retail Distribution Ltd",
      contactName: "Ada Okafor",
      email: "ada@primeretail.ng",
      phone: "+2348090001111",
      status: "approved",
      tier: "growth",
      regions: ["Lagos", "Abuja"],
      accountManagerName: "Kemi Williams",
      accountManagerEmail: "kemi.williams@nestfoodsltd.com",
      accountManagerPhone: "+2348001230001",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "b2b-acct-0002",
      companyName: "Metro Foods Wholesales",
      contactName: "Uche Obi",
      email: "uche@metrofoods.ng",
      phone: "+2348090002222",
      status: "pending_approval",
      tier: "starter",
      regions: ["Port Harcourt"],
      createdAt: now,
      updatedAt: now,
    },
  ],
  quoteRequests: [
    {
      id: "b2b-quote-0001",
      quoteNumber: "B2B-Q-2026-0001",
      accountId: "b2b-acct-0001",
      items: [
        {
          variantId: "var-protein-2kg",
          quantity: 20,
        },
        {
          variantId: "var-signature-rice-1kg",
          quantity: 30,
        },
      ],
      quotedLines: [
        {
          productSlug: "plant-protein-granules",
          productName: "Plant Protein Granules",
          variantId: "var-protein-2kg",
          variantName: "2kg Bulk",
          quantity: 20,
          listPriceMinor: 2500000,
          unitPriceMinor: 2200000,
          lineTotalMinor: 44000000,
          currency: "NGN",
        },
        {
          productSlug: "signature-jollof-rice-mix",
          productName: "Signature Jollof Rice Mix",
          variantId: "var-signature-rice-1kg",
          variantName: "1kg Pack",
          quantity: 30,
          listPriceMinor: 850000,
          unitPriceMinor: 748000,
          lineTotalMinor: 22440000,
          currency: "NGN",
        },
      ],
      summary: {
        currency: "NGN",
        subtotalMinor: 69500000,
        discountMinor: 3076000,
        totalMinor: 66440000,
        estimatedFulfillmentDays: 3,
      },
      notes: "Need split delivery across two warehouses.",
      preferredDeliveryDate: "2026-02-20",
      status: "quoted",
      timeline: [
        {
          status: "submitted",
          at: now,
          note: "Quote submitted by distributor.",
          by: "buyer",
        },
        {
          status: "reviewing",
          at: now,
          note: "Sales manager reviewing stock and logistics.",
          by: "manager",
        },
        {
          status: "quoted",
          at: now,
          note: "Commercial quote shared with distributor.",
          by: "manager",
        },
      ],
      reviewedByRole: "SALES_MANAGER",
      createdAt: now,
      updatedAt: now,
    },
  ],
  orders: [
    {
      id: "b2b-order-0001",
      orderNumber: "B2B-2026-0001",
      accountId: "b2b-acct-0001",
      quoteRequestId: "b2b-quote-0001",
      items: [
        {
          productSlug: "plant-protein-granules",
          productName: "Plant Protein Granules",
          variantId: "var-protein-2kg",
          variantName: "2kg Bulk",
          quantity: 20,
          listPriceMinor: 2500000,
          unitPriceMinor: 2200000,
          lineTotalMinor: 44000000,
          currency: "NGN",
        },
      ],
      summary: {
        currency: "NGN",
        subtotalMinor: 50000000,
        discountMinor: 6000000,
        totalMinor: 44000000,
        estimatedFulfillmentDays: 3,
      },
      status: "in_transit",
      expectedDeliveryAt: "2026-02-18T15:00:00.000Z",
      trackingCode: "NFL-B2B-TRK-001",
      timeline: [
        { status: "received", at: now, note: "Order received from approved quote." },
        { status: "processing", at: now, note: "Warehouse picking in progress." },
        { status: "in_transit", at: now, note: "Shipment dispatched." },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  invoices: [
    {
      id: "b2b-invoice-0001",
      invoiceNumber: "NFL-INV-B2B-0001",
      accountId: "b2b-acct-0001",
      orderId: "b2b-order-0001",
      amountMinor: 44000000,
      paidMinor: 22000000,
      balanceMinor: 22000000,
      currency: "NGN",
      status: "partially_paid",
      issuedAt: "2026-02-12T08:00:00.000Z",
      dueAt: "2026-02-26T08:00:00.000Z",
      fileUrl: "/placeholders/section-image-placeholder.svg",
      updatedAt: now,
    },
  ],
  statements: [
    {
      id: "b2b-statement-2026-01-0001",
      accountId: "b2b-acct-0001",
      periodLabel: "January 2026",
      periodStart: "2026-01-01",
      periodEnd: "2026-01-31",
      totalBilledMinor: 80000000,
      totalPaidMinor: 60000000,
      balanceMinor: 20000000,
      currency: "NGN",
      generatedAt: "2026-02-01T10:00:00.000Z",
      fileUrl: "/placeholders/section-image-placeholder.svg",
    },
  ],
  supportTickets: [
    {
      id: "b2b-ticket-0001",
      accountId: "b2b-acct-0001",
      subject: "Dispatch ETA for Abuja warehouse",
      description: "Need delivery ETA split by warehouse location.",
      channel: "portal",
      priority: "normal",
      status: "in_progress",
      assignedTo: "kemi.williams@nestfoodsltd.com",
      openedAt: now,
      updatedAt: now,
    },
  ],
};
