import { type RecipeData } from "./types";

const now = new Date().toISOString();

export const RECIPE_SEED_DATA: RecipeData = {
  recipes: [
    {
      id: "recipe-0001",
      slug: "power-jollof-protein-bowl",
      title: "Power Jollof Protein Bowl",
      description:
        "High-protein jollof-inspired bowl combining signature rice mix and plant protein granules.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 12,
      cookMinutes: 20,
      servings: 4,
      ingredients: [
        "signature jollof rice mix",
        "plant protein granules",
        "tomato paste",
        "onions",
        "bell pepper",
        "vegetable oil",
        "garlic",
      ],
      steps: [
        "Hydrate plant protein granules in warm water for 8 minutes.",
        "Sauté onions, garlic, and tomato paste in oil until aromatic.",
        "Add signature jollof rice mix, water, and bell pepper, then simmer.",
        "Fold in hydrated protein granules and cook until rice is tender.",
        "Rest for 5 minutes and serve hot.",
      ],
      relatedProductSlugs: ["signature-jollof-rice-mix", "plant-protein-granules"],
      tags: ["high-protein", "family-meal", "quick-dinner"],
      nutritionPerServing: {
        calories: 430,
        proteinG: 24,
        carbsG: 52,
        fatG: 12,
      },
      updatedAt: now,
    },
    {
      id: "recipe-0002",
      slug: "fortified-breakfast-crunch",
      title: "Fortified Breakfast Crunch",
      description: "Balanced breakfast bowl featuring super breakfast cereal with fruit topping.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 6,
      cookMinutes: 0,
      servings: 2,
      ingredients: ["super breakfast cereal", "milk", "banana", "peanuts", "honey"],
      steps: [
        "Portion super breakfast cereal into bowls.",
        "Slice banana and sprinkle over cereal.",
        "Add chilled milk and top with peanuts and honey.",
      ],
      relatedProductSlugs: ["super-breakfast-cereal"],
      tags: ["breakfast", "kids-friendly", "fortified"],
      nutritionPerServing: {
        calories: 360,
        proteinG: 13,
        carbsG: 48,
        fatG: 11,
      },
      updatedAt: now,
    },
    {
      id: "recipe-0003",
      slug: "weekday-protein-wrap",
      title: "Weekday Protein Wrap",
      description: "Fast lunch wrap with plant protein granules and pepper relish.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 10,
      cookMinutes: 10,
      servings: 3,
      ingredients: [
        "plant protein granules",
        "wrap",
        "lettuce",
        "yogurt",
        "pepper relish",
        "onions",
      ],
      steps: [
        "Sauté onions and hydrated protein granules for 6 minutes.",
        "Warm wraps lightly and layer lettuce and relish.",
        "Add protein mix and finish with yogurt drizzle.",
      ],
      relatedProductSlugs: ["plant-protein-granules"],
      tags: ["lunch", "quick", "high-protein"],
      nutritionPerServing: {
        calories: 390,
        proteinG: 20,
        carbsG: 39,
        fatG: 16,
      },
      updatedAt: now,
    },
  ],
};
