import { type RecipeData } from "./types";

const now = new Date().toISOString();

export const RECIPE_SEED_DATA: RecipeData = {
  recipes: [
    {
      id: "recipe-0001",
      slug: "golden-egg-bread-toast",
      title: "Golden Egg Bread Toast",
      description:
        "Fast breakfast toast built on classic sandwich bread, eggs, and lightly seasoned vegetables.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 10,
      cookMinutes: 8,
      servings: 4,
      ingredients: [
        "classic sandwich loaf",
        "eggs",
        "butter",
        "onions",
        "bell pepper",
        "black pepper",
      ],
      steps: [
        "Lightly toast the bread slices until the edges turn golden.",
        "Whisk eggs with pepper and sauté onions and bell pepper in butter.",
        "Scramble eggs gently until set and spoon over toasted bread.",
        "Serve warm as a quick breakfast or café-style snack.",
      ],
      relatedProductSlugs: ["classic-sandwich-loaf"],
      tags: ["breakfast", "quick", "bread-based"],
      nutritionPerServing: {
        calories: 290,
        proteinG: 11,
        carbsG: 28,
        fatG: 14,
      },
      updatedAt: now,
    },
    {
      id: "recipe-0002",
      slug: "whole-wheat-garden-sandwich",
      title: "Whole Wheat Garden Sandwich",
      description: "Fresh sandwich idea featuring whole wheat bread, greens, and creamy spread.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 12,
      cookMinutes: 0,
      servings: 2,
      ingredients: ["whole wheat loaf", "lettuce", "tomato", "cucumber", "spread", "pepper"],
      steps: [
        "Slice whole wheat bread evenly and spread with your preferred sandwich dressing.",
        "Layer lettuce, tomato, cucumber, and pepper for a clean fresh stack.",
        "Close, slice, and serve for retail sampling or home lunch inspiration.",
      ],
      relatedProductSlugs: ["whole-wheat-loaf"],
      tags: ["fresh", "healthy", "sandwich"],
      nutritionPerServing: {
        calories: 260,
        proteinG: 9,
        carbsG: 34,
        fatG: 9,
      },
      updatedAt: now,
    },
    {
      id: "recipe-0003",
      slug: "butter-loaf-bread-pudding-cups",
      title: "Butter Loaf Bread Pudding Cups",
      description: "A richer dessert-style idea using butter loaf cubes, milk, and warm spice notes.",
      imageUrl: "/placeholders/section-image-placeholder.svg",
      status: "published",
      prepMinutes: 15,
      cookMinutes: 20,
      servings: 3,
      ingredients: [
        "butter top loaf",
        "milk",
        "egg",
        "sugar",
        "cinnamon",
        "raisins",
      ],
      steps: [
        "Cube the butter loaf and soak lightly in milk and beaten egg.",
        "Fold in sugar, cinnamon, and raisins, then portion into cups.",
        "Bake until set and lightly golden on top.",
      ],
      relatedProductSlugs: ["butter-top-loaf"],
      tags: ["dessert", "premium", "bread-based"],
      nutritionPerServing: {
        calories: 340,
        proteinG: 8,
        carbsG: 42,
        fatG: 14,
      },
      updatedAt: now,
    },
  ],
};
