import { type CmsData } from "./types";

const now = new Date().toISOString();

export const CMS_SEED_DATA: CmsData = {
  pages: {
    home: {
      slug: "home",
      title: "De-Nest Bread",
      headline: "Baking memories, one slice at a time.",
      description:
        "De-Nest Bread is the public bread brand of Nest Foods Limited. Baking memories, one slice at a time. Every loaf is a testament of our commitment to quality.",
      status: "published",
      publishAt: now,
      ctaPrimaryLabel: "Explore Products",
      ctaPrimaryHref: "/shop",
      ctaSecondaryLabel: "Contact Team",
      ctaSecondaryHref: "/contact",
      heroMediaKind: "image",
      heroImageUrl: "/placeholders/hero/hero-image-placeholder.svg",
      heroVideoPosterUrl: "/placeholders/hero/hero-video-poster-placeholder.svg",
      logoImageUrl: "/brand/logos/logo-primary.svg",
      seo: {
        title: "De-Nest Bread | Premium Bread Manufacturer",
        description:
          "Premium bread products, production standards, and company information from Nest Foods Limited.",
        ogImageUrl: "/seo/og/default-og.svg",
      },
      updatedAt: now,
      revisions: [],
    },
    about: {
      slug: "about",
      title: "About Nest Foods Limited",
      headline: "A Nigerian bakery built on quality, consistency, and trust.",
      description:
        "Nest Foods Limited Awka was established in 2022 to meet demand for locally produced, affordable, rich, and quality bakery products.",
      status: "published",
      publishAt: now,
      heroMediaKind: "image",
      heroImageUrl: "/placeholders/sections/section-image-placeholder.svg",
      logoImageUrl: "/brand/logos/logo-primary.svg",
      seo: {
        title: "About Nest Foods Limited",
        description: "Learn about Nest Foods Limited, the company behind De-Nest Bread.",
        ogImageUrl: "/seo/og/default-og.svg",
      },
      updatedAt: now,
      revisions: [],
    },
    vision: {
      slug: "vision",
      title: "Vision & Mission",
      headline: "To become the leading company in bakery and confectioneries industry.",
      description:
        "Nest Foods Limited produces baked products and confectioneries under the most hygienic conditions with best natural ingredients for human nourishment.",
      status: "published",
      publishAt: now,
      heroMediaKind: "image",
      heroImageUrl: "/placeholders/sections/section-image-placeholder.svg",
      logoImageUrl: "/brand/logos/logo-primary.svg",
      seo: {
        title: "Vision & Mission | De-Nest Bread",
        description: "Explore the mission, vision, and values behind De-Nest Bread.",
        ogImageUrl: "/seo/og/default-og.svg",
      },
      updatedAt: now,
      revisions: [],
    },
    contact: {
      slug: "contact",
      title: "Contact Nest Foods Limited",
      headline: "Speak with the Nest Foods Limited team.",
      description:
        "Use this page for product enquiries, office contacts, confirmed social channels, and career contact details.",
      status: "published",
      publishAt: now,
      heroMediaKind: "image",
      heroImageUrl: "/placeholders/sections/section-image-placeholder.svg",
      logoImageUrl: "/brand/logos/logo-primary.svg",
      seo: {
        title: "Contact Nest Foods Limited",
        description: "Reach Nest Foods Limited for De-Nest Bread product and company enquiries.",
        ogImageUrl: "/seo/og/default-og.svg",
      },
      updatedAt: now,
      revisions: [],
    },
    careers: {
      slug: "careers",
      title: "Careers",
      headline: "Join the team behind De-Nest Bread.",
      description:
        "Nest Foods Limited welcomes career enquiries across production, management, accounting, sales, marketing and distribution, driving, cleaning, and support roles.",
      status: "published",
      publishAt: now,
      heroMediaKind: "image",
      heroImageUrl: "/placeholders/sections/section-image-placeholder.svg",
      logoImageUrl: "/brand/logos/logo-primary.svg",
      seo: {
        title: "Careers at Nest Foods Limited",
        description: "Career guidance and HR contacts for Nest Foods Limited.",
        ogImageUrl: "/seo/og/default-og.svg",
      },
      updatedAt: now,
      revisions: [],
    },
  },
  banners: [
    {
      id: "banner-home-1",
      label: "Product Guidance",
      headline: "Review De-Nest Bread products and contact Nest Foods Limited from one place.",
      ctaLabel: "Contact Team",
      ctaHref: "/contact",
      imageUrl: "/placeholders/hero/hero-image-placeholder.svg",
      status: "published",
      publishAt: now,
      order: 1,
      updatedAt: now,
    },
  ],
  media: [
    {
      id: "media-logo-primary",
      label: "Primary Logo Placeholder",
      kind: "image",
      url: "/brand/logos/logo-primary.svg",
      altText: "De-Nest Bread logo",
      folder: "branding",
      updatedAt: now,
    },
    {
      id: "media-hero-default",
      label: "Hero Image Placeholder",
      kind: "image",
      url: "/placeholders/hero/hero-image-placeholder.svg",
      altText: "De-Nest Bread hero visual",
      folder: "homepage",
      updatedAt: now,
    },
    {
      id: "media-hero-video-poster",
      label: "Hero Video Poster Placeholder",
      kind: "image",
      url: "/placeholders/hero/hero-video-poster-placeholder.svg",
      altText: "De-Nest Bread hero video poster",
      folder: "homepage",
      updatedAt: now,
    },
  ],
};
