import { type TraceabilityData } from "./types";

const now = new Date().toISOString();

export const TRACEABILITY_SEED_DATA: TraceabilityData = {
  batches: [
    {
      id: "trace-batch-0001",
      batchCode: "NFL-BREAD-260301-A",
      qrCode: "https://nestfoodsltd.com/traceability?code=NFL-BREAD-260301-A",
      productSlug: "classic-sandwich-loaf",
      productName: "Classic Sandwich Loaf",
      variantId: "var-classic-loaf-800g",
      status: "active",
      productionDate: "2026-03-01",
      expiryDate: "2026-03-08",
      source: {
        farmName: "Golden Wheat Milling Cooperative",
        region: "Kaduna",
        country: "Nigeria",
        lotReference: "GWM-KAD-2602-LOT11",
        harvestedAt: "2026-02-18",
      },
      processing: {
        facilityName: "Nest Foods Bread Plant, Lagos",
        lineName: "Sliced Bread Line 1",
        packagedAt: "2026-03-01T10:10:00.000Z",
        qaLead: "Mariam Yusuf",
      },
      certifications: [
        {
          id: "cert-0001",
          name: "NAFDAC Listing",
          issuer: "NAFDAC",
          certificateCode: "NAFDAC-RF-2026-4421",
          validUntil: "2027-01-31",
        },
        {
          id: "cert-0002",
          name: "ISO 22000",
          issuer: "SGS",
          certificateCode: "ISO22000-NFL-2026",
          validUntil: "2028-06-30",
        },
      ],
      timeline: [
        {
          id: "evt-0001",
          stage: "sourcing",
          title: "Flour and ingredient intake",
          description: "Flour, yeast, and supporting ingredients were received with lot-level quality checks.",
          location: "Kaduna Aggregation Center",
          startedAt: "2026-02-19T08:00:00.000Z",
          completedAt: "2026-02-19T14:30:00.000Z",
        },
        {
          id: "evt-0002",
          stage: "processing",
          title: "Mixing, proofing, and baking",
          description: "Dough was processed to target proofing, bake color, and loaf structure specifications.",
          location: "Lagos Bread Line 1",
          startedAt: "2026-03-01T05:45:00.000Z",
          completedAt: "2026-03-01T09:20:00.000Z",
        },
        {
          id: "evt-0003",
          stage: "quality_check",
          title: "QA release approved",
          description: "Weight, slice integrity, sealing quality, and microbiology checks passed release criteria.",
          location: "Lagos QA Lab",
          startedAt: "2026-03-01T09:45:00.000Z",
          completedAt: "2026-03-01T12:20:00.000Z",
        },
        {
          id: "evt-0004",
          stage: "distribution",
          title: "Shipment dispatched",
          description: "Batch routed to Lagos and Abuja distribution centers for retail delivery windows.",
          location: "Lagos Central Warehouse",
          startedAt: "2026-03-01T14:00:00.000Z",
          completedAt: "2026-03-01T16:15:00.000Z",
        },
      ],
      adminNotes: "Priority batch for retail quality showcase.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "trace-batch-0002",
      batchCode: "NFL-BUTTER-260304-B",
      qrCode: "https://nestfoodsltd.com/traceability?code=NFL-BUTTER-260304-B",
      productSlug: "butter-top-loaf",
      productName: "Butter Top Loaf",
      variantId: "var-butter-loaf-700g",
      status: "active",
      productionDate: "2026-03-04",
      expiryDate: "2026-03-10",
      source: {
        farmName: "Southern Grain Partners",
        region: "Ogun",
        country: "Nigeria",
        lotReference: "SGP-OGN-2602-LOT08",
        harvestedAt: "2026-02-20",
      },
      processing: {
        facilityName: "Nest Foods Bread Plant, Ogun",
        lineName: "Premium Bread Line 2",
        packagedAt: "2026-03-04T09:25:00.000Z",
        qaLead: "Chinedu Eze",
      },
      certifications: [
        {
          id: "cert-0003",
          name: "HACCP Compliance",
          issuer: "SON",
          certificateCode: "HACCP-NFL-2026-129",
          validUntil: "2027-03-31",
        },
      ],
      timeline: [
        {
          id: "evt-0005",
          stage: "sourcing",
          title: "Ingredient lots received",
          description: "Approved flour and dairy-supporting inputs were logged with trace records.",
          location: "Ogun Intake Hub",
          startedAt: "2026-02-24T08:00:00.000Z",
          completedAt: "2026-02-24T13:00:00.000Z",
        },
        {
          id: "evt-0006",
          stage: "processing",
          title: "Mixing, baking, and cooling",
          description: "Premium loaf batch baked to target top finish, moisture profile, and packaging readiness.",
          location: "Ogun Bread Plant",
          startedAt: "2026-03-04T05:55:00.000Z",
          completedAt: "2026-03-04T11:30:00.000Z",
        },
        {
          id: "evt-0007",
          stage: "quality_check",
          title: "Premium finish release",
          description: "Appearance, sealing, and microbial profile were validated before dispatch.",
          location: "Ogun QA Lab",
          startedAt: "2026-03-04T12:00:00.000Z",
          completedAt: "2026-03-04T15:45:00.000Z",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
};
