import { type TraceabilityData } from "./types";

const now = new Date().toISOString();

export const TRACEABILITY_SEED_DATA: TraceabilityData = {
  batches: [
    {
      id: "trace-batch-0001",
      batchCode: "NFL-JOLLOF-260201-A",
      qrCode: "https://nestfoodsltd.com/traceability?code=NFL-JOLLOF-260201-A",
      productSlug: "signature-jollof-rice-mix",
      productName: "Signature Jollof Rice Mix",
      variantId: "var-signature-rice-1kg",
      status: "active",
      productionDate: "2026-02-01",
      expiryDate: "2027-02-01",
      source: {
        farmName: "Savannah Grain Cooperative",
        region: "Kaduna",
        country: "Nigeria",
        lotReference: "SGC-KAD-2601-LOT11",
        harvestedAt: "2026-01-15",
      },
      processing: {
        facilityName: "Nest Foods Lagos Processing Hub",
        lineName: "Rice Mix Line 2",
        packagedAt: "2026-02-01T10:10:00.000Z",
        qaLead: "Mariam Yusuf",
      },
      certifications: [
        {
          id: "cert-0001",
          name: "NAFDAC Listing",
          issuer: "NAFDAC",
          certificateCode: "NAFDAC-RF-2026-4421",
          validUntil: "2027-01-31",
        },
        {
          id: "cert-0002",
          name: "ISO 22000",
          issuer: "SGS",
          certificateCode: "ISO22000-NFL-2026",
          validUntil: "2028-06-30",
        },
      ],
      timeline: [
        {
          id: "evt-0001",
          stage: "sourcing",
          title: "Raw material sourced",
          description: "Rice and spice materials received with lot-level quality checks.",
          location: "Kaduna Aggregation Center",
          startedAt: "2026-01-16T08:00:00.000Z",
          completedAt: "2026-01-16T14:30:00.000Z",
        },
        {
          id: "evt-0002",
          stage: "processing",
          title: "Batch mixed and packaged",
          description: "Standardized mix ratio validated and packed for retail distribution.",
          location: "Lagos Production Line 2",
          startedAt: "2026-02-01T07:00:00.000Z",
          completedAt: "2026-02-01T12:00:00.000Z",
        },
        {
          id: "evt-0003",
          stage: "quality_check",
          title: "QA release approved",
          description: "Microbiology and moisture checks passed batch release criteria.",
          location: "Lagos QA Lab",
          startedAt: "2026-02-01T12:15:00.000Z",
          completedAt: "2026-02-01T15:20:00.000Z",
        },
        {
          id: "evt-0004",
          stage: "distribution",
          title: "Shipment dispatched",
          description: "Batch routed to Lagos and Abuja distribution centers.",
          location: "Lagos Central Warehouse",
          startedAt: "2026-02-02T09:00:00.000Z",
          completedAt: "2026-02-02T11:15:00.000Z",
        },
      ],
      adminNotes: "Priority batch for Q1 campaign.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "trace-batch-0002",
      batchCode: "NFL-PROTEIN-260203-B",
      qrCode: "https://nestfoodsltd.com/traceability?code=NFL-PROTEIN-260203-B",
      productSlug: "plant-protein-granules",
      productName: "Plant Protein Granules",
      variantId: "var-protein-2kg",
      status: "active",
      productionDate: "2026-02-03",
      expiryDate: "2026-11-01",
      source: {
        farmName: "Benue Soy Collective",
        region: "Benue",
        country: "Nigeria",
        lotReference: "BSC-BEN-2602-LOT08",
        harvestedAt: "2026-01-22",
      },
      processing: {
        facilityName: "Nest Foods Protein Facility",
        lineName: "Protein Extrusion Line 1",
        packagedAt: "2026-02-03T09:25:00.000Z",
        qaLead: "Chinedu Eze",
      },
      certifications: [
        {
          id: "cert-0003",
          name: "HACCP Compliance",
          issuer: "SON",
          certificateCode: "HACCP-NFL-2026-129",
          validUntil: "2027-03-31",
        },
      ],
      timeline: [
        {
          id: "evt-0005",
          stage: "sourcing",
          title: "Soy lots received",
          description: "Approved suppliers delivered soybean lots with trace records.",
          location: "Makurdi Intake Hub",
          startedAt: "2026-01-25T08:00:00.000Z",
          completedAt: "2026-01-25T13:00:00.000Z",
        },
        {
          id: "evt-0006",
          stage: "processing",
          title: "Extrusion and drying",
          description: "Granules extruded and dried to target moisture profile.",
          location: "Ogun Protein Plant",
          startedAt: "2026-02-03T06:10:00.000Z",
          completedAt: "2026-02-03T12:30:00.000Z",
        },
        {
          id: "evt-0007",
          stage: "quality_check",
          title: "Protein assay pass",
          description: "Protein concentration and microbial profile validated.",
          location: "Ogun QA Lab",
          startedAt: "2026-02-03T13:00:00.000Z",
          completedAt: "2026-02-03T16:45:00.000Z",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
};
