import { type CommerceData } from "./types";

const now = new Date().toISOString();

export const COMMERCE_SEED_DATA: CommerceData = {
  products: [
    {
      id: "prod-classic-sandwich-loaf",
      slug: "classic-sandwich-loaf",
      status: "published",
      availabilityStatus: "available",
      availableRegions: ["Lagos", "Abuja", "Port Harcourt", "Kano"],
      minimumOrderQuantity: 40,
      maximumOrderQuantity: 6000,
      name: "Classic Sandwich Loaf",
      category: "Sliced Bread",
      shortDescription: "Soft, evenly sliced bread for everyday retail, school, and household use.",
      longDescription:
        "A dependable family loaf baked for consistent crumb structure, clean slicing, and shelf-ready presentation across supermarkets, distributors, and institutional buyers.",
      imageUrl: "/placeholders/product-image-placeholder.svg",
      galleryUrls: [
        "/placeholders/product-image-placeholder.svg",
        "/placeholders/section-image-placeholder.svg",
      ],
      tags: ["best-seller", "daily-staple", "retail-ready"],
      allergens: ["Contains wheat gluten"],
      ingredients: ["Wheat flour", "Water", "Sugar", "Yeast", "Vegetable oil", "Iodized salt"],
      shelfLifeDays: 7,
      nutritionTable: [
        { label: "Energy", amount: 252, unit: "kcal" },
        { label: "Protein", amount: 8.1, unit: "g" },
        { label: "Carbohydrates", amount: 47, unit: "g" },
        { label: "Fat", amount: 3.6, unit: "g" },
      ],
      variants: [
        {
          id: "var-classic-loaf-800g",
          name: "800g Family Loaf",
          sku: "NFL-BRD-800G",
          sizeLabel: "800g",
          stockStatus: "in_stock",
          priceMinor: 320000,
          currency: "NGN",
        },
        {
          id: "var-classic-loaf-400g",
          name: "400g Compact Loaf",
          sku: "NFL-BRD-400G",
          sizeLabel: "400g",
          stockStatus: "in_stock",
          priceMinor: 180000,
          currency: "NGN",
        },
      ],
      updatedAt: now,
    },
    {
      id: "prod-butter-top-loaf",
      slug: "butter-top-loaf",
      status: "published",
      availabilityStatus: "limited",
      availableRegions: ["Lagos", "Abuja"],
      minimumOrderQuantity: 50,
      maximumOrderQuantity: 4500,
      name: "Butter Top Loaf",
      category: "Premium Bread",
      shortDescription: "Golden-finished loaf with a softer crumb and richer premium positioning.",
      longDescription:
        "A richer bread line designed for shelves that need a more premium presentation, smooth slicing performance, and dependable repeat quality.",
      imageUrl: "/placeholders/product-image-placeholder.svg",
      galleryUrls: ["/placeholders/product-image-placeholder.svg"],
      tags: ["premium", "b2b-ready"],
      allergens: ["Contains wheat gluten", "Contains milk"],
      ingredients: ["Wheat flour", "Water", "Milk solids", "Sugar", "Yeast", "Butter flavor"],
      shelfLifeDays: 6,
      nutritionTable: [
        { label: "Energy", amount: 286, unit: "kcal" },
        { label: "Protein", amount: 8.4, unit: "g" },
        { label: "Carbohydrates", amount: 49, unit: "g" },
        { label: "Fat", amount: 5.7, unit: "g" },
      ],
      variants: [
        {
          id: "var-butter-loaf-700g",
          name: "700g Family Loaf",
          sku: "NFL-BTR-700G",
          sizeLabel: "700g",
          stockStatus: "in_stock",
          priceMinor: 420000,
          currency: "NGN",
        },
        {
          id: "var-butter-loaf-350g",
          name: "350g Compact Loaf",
          sku: "NFL-BTR-350G",
          sizeLabel: "350g",
          stockStatus: "low_stock",
          priceMinor: 240000,
          currency: "NGN",
        },
      ],
      updatedAt: now,
    },
    {
      id: "prod-whole-wheat-loaf",
      slug: "whole-wheat-loaf",
      status: "published",
      availabilityStatus: "available",
      availableRegions: ["Lagos", "Abuja", "Port Harcourt"],
      minimumOrderQuantity: 30,
      maximumOrderQuantity: 3500,
      name: "Whole Wheat Loaf",
      category: "Health Range",
      shortDescription: "High-fibre loaf built for nutrition-conscious households and modern retail shelves.",
      longDescription:
        "A whole-wheat bread line developed for buyers who need a better-for-you option with dependable shelf presentation, clean labeling, and consistent texture.",
      imageUrl: "/placeholders/product-image-placeholder.svg",
      galleryUrls: [
        "/placeholders/product-image-placeholder.svg",
        "/placeholders/section-image-placeholder.svg",
      ],
      tags: ["high-fibre", "fortified", "family-pack"],
      allergens: ["Contains wheat gluten", "May contain sesame"],
      ingredients: ["Whole wheat flour", "Water", "Bran", "Yeast", "Sugar", "Salt"],
      shelfLifeDays: 6,
      nutritionTable: [
        { label: "Energy", amount: 241, unit: "kcal" },
        { label: "Protein", amount: 9.3, unit: "g" },
        { label: "Carbohydrates", amount: 42, unit: "g" },
        { label: "Fat", amount: 3.8, unit: "g" },
      ],
      variants: [
        {
          id: "var-wholewheat-loaf-750g",
          name: "750g Family Loaf",
          sku: "NFL-WWL-750G",
          sizeLabel: "750g",
          stockStatus: "in_stock",
          priceMinor: 390000,
          currency: "NGN",
        },
        {
          id: "var-wholewheat-loaf-375g",
          name: "375g Compact Loaf",
          sku: "NFL-WWL-375G",
          sizeLabel: "375g",
          stockStatus: "in_stock",
          priceMinor: 220000,
          currency: "NGN",
        },
      ],
      updatedAt: now,
    },
  ],
};
